# nginx proxy address - http://172.17.0.1:8107

name: lufi
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  lufi:
    image: silkeh/lufi:latest
    pull_policy: always
    container_name: lufi-app
    restart: always
    logging: *default-logging
    networks:
      - lufi
    ports:
      - "172.17.0.1:8107:8080"
    environment:
      TZ: ${TZ:-America/New_York}
      LUFI_CONTACT: ${APP_ADMIN_USER:-admin}@${BASE_DOMAIN_NAME:-example.com}
      LUFI_SECRETS: ${APP_SECRET_KEY:-changeme_secret_key_min_32_chars}
      LUFI_MAX_FILE_SIZE: 104857600
      LUFI_DEFAULT_DELAY: 0
      LUFI_MAX_DELAY: 0
    volumes:
      - ./volumes/config/lufi:/lufi/config
      - ./volumes/data/lufi:/lufi/files

networks:
  lufi:
    name: lufi
    external: false
